import styles from "@/styles/Home.module.css";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Inter } from "@next/font/google";
import Head from "next/head";
import React from "react";
import { _Menu } from "./menu";

const inter = Inter({ subsets: ["latin"] });

const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
});

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ThemeProvider theme={darkTheme}>
          <>
            <div>
              <_Menu />
            </div>
            <div>{children}</div>
          </>
        </ThemeProvider>
      </main>
    </>
  );
}
