import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import { _Menu } from "./menu";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <_Menu />
        </div>
        <div>{children}</div>
      </main>
    </>
  );
}
